import type { AnalysisResultData, RepositoryInfo } from '../overview/api';
import { ReportPage } from '../findings/use-analysis-report';
import { sourceHref } from '../architecture/source-links';

function TestingResults({ repository, analysis }: { repository: RepositoryInfo; analysis: AnalysisResultData }) {
  const data = analysis.schema_version === 2 ? analysis.testing : null;
  if (!data) return <section className="report-section"><h2>Testing data unavailable</h2><p className="report-muted">This report version does not include test discovery or coverage fields.</p></section>;
  return <><div className="report-metrics"><article><span>Discovered test files</span><strong>{data.test_files.length}</strong><small>File discovery is not execution or coverage.</small></article><article><span>Actual coverage</span><strong>{data.coverage ? `${data.coverage.percent}%` : 'Not supplied'}</strong><small>{data.coverage ? `${data.coverage.covered} / ${data.coverage.total} ${data.coverage.metric} · ${data.coverage.format}` : `Coverage status: ${data.coverage_status}`}</small></article><article><span>Service candidates</span><strong>{data.services.length}</strong><small>Static candidates are not measured test results.</small></article></div>
    <section className="report-section"><h2>Discovered tests</h2>{data.test_files.length ? <ul className="report-rows">{data.test_files.map((file) => <li key={file.path}><a href={sourceHref(repository, file.path, 1) ?? undefined}>{file.path}</a><span>{file.framework ?? 'Framework not identified'} · {file.declaration_count} declarations</span></li>)}</ul> : <div className="report-empty"><strong>No test files discovered</strong><p>Discovery results do not establish whether tests are missing or failing.</p></div>}</section>
    <section className="report-section"><h2>Services without a linked test path</h2>{data.services.filter((service) => !service.test_paths.length).length ? <ul className="report-rows">{data.services.filter((service) => !service.test_paths.length).map((service) => <li key={`${service.path}:${service.name}`}><div><strong>{service.name}</strong><span>{service.path}:{service.location.start_line}</span></div><span>Missing linked test path</span></li>)}</ul> : <p className="report-muted">No service candidates were reported without linked test paths.</p>}</section>
    {data.coverage_errors.length > 0 && <section className="report-section"><h2>Coverage import notes</h2><ul>{data.coverage_errors.map((error, index) => <li key={index}>{error}</li>)}</ul></section>}</>;
}
export function TestingPage({ repositoryId }: { repositoryId: string }) { return <ReportPage repositoryId={repositoryId} eyebrow="TESTING REPORT" title="Testing">{(repository, analysis) => <TestingResults repository={repository} analysis={analysis}/>}</ReportPage>; }
